### ISSUE TITLE
How do specify a last step ?

### ISSUE THREAD

**Issue by Anenth** [LeadDyno/bootstrap-nav-wizard#4]
when you have just 3 steps how do i make the last step as style same as the 1st step ?

**Comment by carsongross** [comment]
You could edit the 

    &:before {
      .chevron-comp(@border-color);
      right: -16px;
    }
    &:after {
      .chevron-comp(@wizard-background);
      right: -15px;
    }

components to be the same and get the same look and feel on both sides.
